server:
  servlet:
    context-path: /mss-api
  port: 8081

spring:
  application:
    name: mars-scavenging-station-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/mss-db
    username: postgres
    password:
  flyway:
    enabled: true
    locations: classpath:db/migration
    create-schemas: true
    default-schema: public

mss:
  storage-capacity: 1000
